---
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: kafka-exporter
        static_configs:
          - targets:
            - kafka-metrics.default:9308
server:
 service:
    type: NodePort
    nodePort: 30001
